### ISSUE TITLE
Custom docker does not generate aflforkserver.so file

### ISSUE THREAD

**Issue by hyeonminmo** [sslab-gatech/autofz#2]
I ran the command `autofz -o output -T 24h -f afl fairfuzz aflfast qsym -t exiv2` within a newly created autofz Docker image, but it's failing with an error indicating that `aflforkserver.so` is missing.

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/autofz/evaluator.py", line 423, in process_loop
    self.afl = AFLForkserverExecuter(self.binary, self.binary_arguments)
  File "/usr/local/lib/python3.9/site-packages/autofz/evaluator.py", line 280, in __init__
    self.aflforkserverlib = ctypes.cdll.LoadLibrary(
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/autofz/aflforkserver.so: cannot open shared object file: No such file or directory
Process Process-2:
...
```

There were two main changes I made when creating the new autofz Docker image:

First, I changed the tag name from **'autofz'** to **'autofz_2**' at `build.sh`.

Second, I made changes related to site connectivity issues.
So, I changed the site '**keyserver.ubuntu.com '** to **'hkp://keyserver.ubuntu.com:80'** at `docker/fuzzer_base/base/Dockerfile` , `docker/fuzzer_base/qsym/Dockerfile` and `Dockerfile` .

I searched, but I couldn't find `aflforkserver.so` in your GitHub `autofz `folder.
I'm also curious if it should be generated during the Docker build process.

Please provide guidance on how to generate `aflforkserver.so` .

**Comment by fuyu0425** [comment]
Hi, I added the file in the commit d74770568359268e874b1d3af96c53ffdcca5e0d.
Sorry, it was ignored by the `.gitignore` file before and I didn't catch it.

The file is actually generated by compiling `https://github.com/egueler/quickcov` used by CUPID.

**Comment by hyeonminmo** [comment]
Thank you for the quick feedback.

 Best regards,
Hyeonmin Mo
2023년 9월 14일 (목) 오전 1:29, Yu-Fu Fu ***@***.***>님이 작성:
