### ISSUE TITLE
`nm` command with `unibench/general_evaluation/obj` as seeds print no symbols

### ISSUE THREAD

**Issue by chinggg** [sslab-gatech/autofz#3]
As https://github.com/sslab-gatech/autofz/blob/main/autofz/config.py shows, `nm` and `objdump` use object files from [`docker/benchmark/seeds/unibench/general_evaluation/obj`](https://github.com/sslab-gatech/autofz/tree/main/docker/benchmark/seeds/unibench/general_evaluation/obj) as seeds and `-A -a -l -S -s --special-syms --synthetic --with-symbol-versions -D @@` as args.
But I find `nm -A -a -l -S -s --special-syms --synthetic --with-symbol-versions -D` produce "no symbols" for all the seed object files. `afl-cmin` shows that the corpus can be trimmed to only one file, which means this fuzzer setup may only reach same limited coverage on each file of the corpus.
```
binutils-2.28$ ./binutils/nm-new -A -a -l -S -s --special-syms --synthetic --with-symbol-versions -D ../autofz/docker/benchmark/seeds/unibench/general_evaluation/obj/*.o        
./binutils/nm-new: ../autofz/docker/benchmark/seeds/unibench/general_evaluation/obj/addr2line.o: no symbols
./binutils/nm-new: ../autofz/docker/benchmark/seeds/unibench/general_evaluation/obj/arlex.o: no symbols
./binutils/nm-new: ../autofz/docker/benchmark/seeds/unibench/general_evaluation/obj/ar.o: no symbols
...
```

I am not sure if the arguments are intentionally set to be `-A -a -l -S -s --special-syms --synthetic --with-symbol-versions -D @@`. I find that `nm` with no `-D` argument can have more verbose output with symbols, though I am not sure it leads to more coverage.

**Comment by fuyu0425** [comment]
https://github.com/sslab-gatech/autofz/blob/d74770568359268e874b1d3af96c53ffdcca5e0d/docker/benchmark/afl/build_all.sh#L222

the `nm` we use is from `binutils-5279478` not `binutils-2.28`.

you can check https://github.com/unifuzz/unibench
