### ISSUE TITLE
How to fix libcgroup initialization failed:Cgroup is not mounted

### ISSUE THREAD

**Issue by hyeonminmo** [sslab-gatech/autofz#4]
This error occurs when you run sudo /init.sh after creating Custom Docker.

```
$ sudo /init.sh
performance
+ cgcreate -t autofz -a autofz -g cpu:/autofz
cgcreate: libcgroup initialization failed: Cgroup is not mounted
```

I tried the Cgroup V2 solution that you wrote in github, 

> [Cgroups V2]
> For a system that is using cgroup v2, a manual downgrade to v1 is necessary. This can be done by adding `systemd.unified_cgroup_hierarchy=0` to the kernel command line (e.g., via /etc/default/grub).

```
# /etc/default/grub
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
```
but the same error message is generated.

```
$ sudo /init.sh
performance
+ cgcreate -t autofz -a autofz -g cpu:/autofz
cgcreate: libcgroup initialization failed: Cgroup is not mounted
```

Please provide guidance on how to fix this error.

**Comment by fuyu0425** [comment]
Have you run `update-grub` to update your boot entries and reboot?

If yes, can you provide the specs of your host environment?

**Comment by hyeonminmo** [comment]
Yes. I have run update-grub to update.

My environment :
OS : Ubuntu 22.04
CPU : AMD EPYC 7763 64-Core Processor * 2

**Comment by fuyu0425** [comment]
I installed a fresh Ubuntu 22.04 and it works for me.

Did you reboot?

`systemd.unified_cgroup_hierarchy=0` should appear in `/proc/cmdline`

```
yufu@autofz-test:~$ cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-5.15.0-84-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro systemd.unified_cgroup_hierarchy=0
```

**Comment by hyeonminmo** [comment]
It's been solved.

Thank you.
