### ISSUE TITLE
genhtml: ERROR: cannot read 

### ISSUE THREAD

**Issue by hyeonminmo** [sslab-gatech/autofz#5]
When I ran `afl-cov` after `autofz `the _objdump_ program, I'm encountering a "genhtml:ERROR: cannnot read" issue. 

```
# Issue message
genhtml: ERROR: cannot read /autofz_bench/unibench/binutils-2.28/bfd/bfd.h
```

I checked the `/autofz_bench/unibench/binutils-2.28/bfd/bfd.h` file, it did not exist.

As a result, the 'index.html' file is not being generated.

The command I used is as follows:
```
$afl-cov --output output_objdump \
 -d output_objdump/objdump -t queue \
 --input /seeds/unibench/general_evaluation/obj \
  --coverage-cmd='/d/p/cov/unibench/objdump/objdump -S @@' \
 --code-dir /autofz_bench/unibench/binutils-2.28 \
 -T 1s --cover-corpus \
 --ignore-core-pattern --overwrite --enable-branch-coverage
```

My environment is 
OS : Ubuntu 22.04
Docker : custom docker 

There are only two changes to the custom docker.
1. Renaming docker tag
2.  Made changes related to site connectivity issues.
So, I changed the site `keyserver.ubuntu.com`  to `hkp://keyserver.ubuntu.com:80` at `docker/fuzzer_base/base/Dockerfile` , `docker/fuzzer_base/qsym/Dockerfile` and `Dockerfile` .

So I wonder how to solve it.

**Comment by fuyu0425** [comment]
These are the relevant files and building scripts.

https://github.com/sslab-gatech/autofz/blob/d74770568359268e874b1d3af96c53ffdcca5e0d/Dockerfile#L117

https://github.com/sslab-gatech/autofz/blob/d74770568359268e874b1d3af96c53ffdcca5e0d/docker/benchmark/coverage/build_all.sh#L3-L9

Are you sure there is no build error? (The files should also appear in `autofz_bench/coverage` image generated during building).

The files appear in the provided docker.
