### ISSUE TITLE
round time difference

### ISSUE THREAD

**Issue by LSXCH** [sslab-gatech/autofz#6]
I followed the guide and executed the command
` autofz -o output -T 8h -f afl fairfuzz aflfast qsym -t exiv2`, but from the console display, a total of only 10 rounds have been executed in 8 hours, which is different from the 300/300 set in advance. I want to know if it's normal?
<img width="615" alt="image" src="https://github.com/sslab-gatech/autofz/assets/51190956/25bd94bc-cabe-4419-a618-f615dcf5e038">

**Comment by LSXCH** [comment]
Every round takes 50 minutes

**Comment by fuyu0425** [comment]
It's normal, 300 means giving each fuzzer 300 seconds (5 minutes). 
Not 75 (300/4) seconds for each fuzzer.

**Comment by LSXCH** [comment]
Thanks! And if I add -j to make the number of cpu's the same as the number of fuzzers, then the the time of a prep phase will reduce to 5 minutes?

**Comment by fuyu0425** [comment]
yes

**Comment by LSXCH** [comment]
Got it
