### ISSUE TITLE
Add fuzzer Eclipser error

### ISSUE THREAD

**Issue by LSXCH** [sslab-gatech/autofz#7]
I want to add Eclipser to autofz. 
Eclipser works similarly to QSYM, collaborating with afl-m afl-s to generate seeds. When trying to add it, I encountered an error report:
`Traceback (most recent call last):
  File "/usr/local/bin/autofz", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/autofz/main.py", line 1483, in main
    pause(fuzzer=fuzzer,
  File "/usr/local/lib/python3.9/site-packages/autofz/main.py", line 373, in pause
    fuzzer_driver.main(**kw)
  File "/usr/local/lib/python3.9/site-packages/autofz/fuzzer_driver/main.py", line 81, in main
    controller.pause()
  File "/usr/local/lib/python3.9/site-packages/autofz/fuzzer_driver/eclipser.py", line 299, in pause
    eclipser.pause()
  File "/usr/local/lib/python3.9/site-packages/autofz/fuzzer_driver/fuzzer.py", line 119, in pause
    raise FuzzerDriverException
autofz.fuzzer_driver.fuzzer.FuzzerDriverException`
The pause is faied. And Eclipser is driven by dotnet. Should I make an additional api call to perform a pause operation?
I create fuzzer_driver/eclipser.py,  and most of the contents of the file are the same as QSYM.
[eclipser.txt](https://github.com/sslab-gatech/autofz/files/14603827/eclipser.txt)

**Comment by fuyu0425** [comment]
I think the root cause is this line
https://github.com/sslab-gatech/autofz/blob/d74770568359268e874b1d3af96c53ffdcca5e0d/autofz/fuzzer_driver/fuzzer.py#L58

Are you sure that the process with that pid is alive when you call pause?

**Comment by LSXCH** [comment]
The Eclipser process was not executed.
config.py:
`'eclipser': {
            'input_dir': INPUT_DIR,
            'crash_dir': CRASH_DIR,
            'skip_crash_file': ['README.txt'],
            'afl_based': True,
            'target_root': '/d/p/normal',  # for eclipser
            # afl_command # reuse base afl
            'eclipser_command': 'dotnet /fuzzer/eclipser/build/Eclipser.dll'
        }`

eclipser.py:
`def gen_run_args(self):
        self.check()
        global FUZZER_CONFIG
        # qsym_command = FUZZER_CONFIG['qsym']['qsym_command']
        eclipser_command = FUZZER_CONFIG['eclipser']['eclipser_command']
        args = []
        if self.cgroup_path:
            args += ['cgexec', '-g', f'cpu:{self.cgroup_path}']
        args += [eclipser_command]
        args += ['-i', self.seed]
        args += ['-v', str(2)]
        args += ['-s', self.output]
        args += ['-o', self.output + "/eclipser/"]
        args += ['-p', self.target]
        print(args)
        eclipser_dir = pathlib.Path(self.output + "/eclipser/")
        eclipser_dir.mkdir(parents=True, exist_ok=True)
        print("mkdir done")
        return args`

Then I check the args print:
`['cgexec', '-g', 'cpu:/autofz/eclipser', 'dotnet /fuzzer/eclipser/build/Eclipser.dll', '-i', '/seeds/fuzzer-test-suite/boringssl-2016-02-12', '-v', '2', '-s', '/work/autofz/ecliser1/boringssl-2016-02-12/eclipser', '-o', '/work/autofz/ecliser1/boringssl-2016-02-12/eclipser/eclipser/', '-p', '/d/p/normal/fuzzer-test-suite/boringssl-2016-02-12/boringssl-2016-02-12']`
I copied these and executed them directly in command line with success.
Sorry I can't find why the process is not alive.

**Comment by LSXCH** [comment]
I've solved this problem. I should do `args += ['dotnet', eclipser_command]` in eclipser.py instead of `'eclipser_command': 'dotnet /fuzzer/eclipser/build/Eclipser.dll'`
Thank you so much
