### ISSUE TITLE
Question about testcase sync

### ISSUE THREAD

**Issue by ahuo1** [sslab-gatech/autofz#8]
Hello, thank you for this excellent work. 

I am a fuzzing newbie and have been studying the autofz recently. I have a question I'd like to ask: **How does autofz synchronize the testcases of each fuzzer with others?** 

As far as I know, taking AFL as an example, AFL only reads testcases from the input directory at the initial startup and does not read testcases again during the running process. 

**How does autofz enable AFL to obtain testcases from other fuzzers?**

**Comment by fuyu0425** [comment]
You can check this link.
https://afl-1.readthedocs.io/en/latest/user_guide.html#tips-for-parallel-fuzzing

autofz utilize this feature.

**Comment by ahuo1** [comment]
Thank you very much for your prompt reply! It's helpful!
